import fs from 'node:fs';
import path from 'node:path';
const repo=path.resolve(path.dirname(new URL(import.meta.url).pathname.replace(/^\/(\w:)/,'$1')),'../..');
const read=p=>fs.readFileSync(path.join(repo,p),'utf8');
let checks=0;
function yes(value,name){checks++;if(!value)throw new Error(name);}
const client=read('src/client/java/top/csituka/magicaland/gameplay/client/levitation/UnicornLevitationClient.java');
const session=read('src/client/java/top/csituka/magicaland/gameplay/client/levitation/UnicornLevitationSession.java');
const input=read('src/client/java/top/csituka/magicaland/gameplay/mixin/client/UnicornLevitationInputMixin.java');
const playerInput=read('src/client/java/top/csituka/magicaland/gameplay/mixin/client/UnicornLevitationPlayerInputMixin.java');
const nativeInput=read('src/client/java/top/csituka/magicaland/gameplay/client/levitation/UnicornLevitationNativeInput.java');
const rawInput=read('src/client/java/top/csituka/magicaland/gameplay/client/levitation/UnicornLevitationInput.java');
const travel=read('src/client/java/top/csituka/magicaland/gameplay/mixin/client/UnicornLevitationTravelMixin.java');
const config=JSON.parse(read('src/client/resources/magicaland.gameplay.client.mixins.json'));
for(const name of ['UnicornLevitationInputMixin','UnicornLevitationTravelMixin','UnicornLevitationPlayerInputMixin']) yes(config.client.includes(name),name+' registered');
yes(input.includes('tick(ZF)V')&&input.includes('@At("HEAD")'),'raw input before TAIL overrides');
yes(input.includes('@At("TAIL")')&&input.includes('applyNativeInput(this)'),'active input restores raw axes after vanilla crouch scaling');
yes(!/setPressed|\.pressed\s*=/.test(input+client+nativeInput+playerInput),'saved physical key bindings never overwritten');
yes(nativeInput.includes('if (controlling) input.jumping = false;')&&nativeInput.includes('if (!suppressSneak) return;'),'charging uncrouch remains separate from controlled jump suppression');
yes(client.includes('nativeControl || SESSION.armed() && readInput(client).space()'),'charging Space suppresses crouch, merely prepared Shift does not');
yes(nativeInput.includes('raw.forwardAxis(false)')&&nativeInput.includes('raw.sideAxis(false)'),'unwinds prior crouch before later vanilla item-use factor');
yes(!/sneak\s*\?\s*\.3/.test(rawInput),'Shift never adds a second sneak-speed multiplier');
yes(playerInput.includes('inSneakingPose = false;')&&playerInput.includes('@At("HEAD")'),'old camera crouch state cleared before pose calculation');
yes(playerInput.includes('AbstractClientPlayerEntity;tickMovement()V')&&playerInput.includes('controlledJump(Input input)'),'post-keyboard autojump cannot inject extra controlled jump');
yes(playerInput.includes('abilityResyncCountdown = 0')&&playerInput.includes('PlayerAbilities;allowFlying:Z'),'prepared native-flight toggle prevented without changing permission');
yes(playerInput.includes('extends AbstractClientPlayerEntity')&&playerInput.includes('super(world, profile)')&&!playerInput.includes('@Shadow protected int abilityResyncCountdown'),'inherited countdown uses actual superclass, not an invalid target-only shadow');
yes(travel.includes('@Mixin(PlayerEntity.class)')&&travel.includes('travel(Lnet/minecraft/util/math/Vec3d;)V'),'actual player travel descriptor');
yes(travel.includes('if (UnicornLevitationClient.travel((PlayerEntity)(Object)this)) ci.cancel()'),'only custom travel cancels');
yes(client.includes('if (player != client.player) return false;'),'foreign player cannot mutate prediction');
yes(client.includes('if (movedAge == player.age) return true;'),'once per player tick');
yes((client.match(/player\.move\(/g)||[]).length===1,'one collision-aware move');
yes(client.includes('MovementType.SELF')&&client.includes('player.updateLimbs(false)'),'collision and limb animation preserved');
yes(!/allowFlying\s*=|setFlySpeed|noClip\s*=|fallDistance\s*=|setNoGravity|setInvulnerable|requestTeleport|setPosition/.test(client+playerInput),'no permission/speed/teleport/immunity mutation');
yes((client.match(/\.flying\s*=/g)||[]).length===1&&client.includes('getAbilities().flying = false;'),'only explicit V start can exit native flight; never automatically enable it');
yes(client.indexOf('sendAbilitiesUpdate()')<client.indexOf('SESSION.begin(true)'),'vanilla flight cancellation sent before magic control');
yes(client.includes('(permitNativeFlightExit || !player.getAbilities().flying)')&&!client.includes('!player.getAbilities().allowFlying')&&!client.includes('!player.isCreative()'),'Creative permission allowed; concurrent native flight still guarded');
yes(!/HudRenderCallback|renderHud\(|manaWaiting|SESSION\.mana\(/.test(client),'mana HUD and local exhaustion limits removed');
yes(!/state\.mana\(|\bmana\s*[<=>]/.test(session),'wire compatibility value does not restrict client session');
for(const guard of ['client.getCameraEntity() == player','!RemoteToolClient.active()','!player.hasVehicle()']) yes(client.includes(guard),guard);
yes(client.includes('if (wasEnabled) retry = Math.max(retry, 20);'),'repeated closed feedback cannot indefinitely extend retry');
yes(client.includes('tick - lastSent >= 5'),'lease heartbeat');
yes(client.includes('state.sequence() <= lastState')&&client.includes('client.getNetworkHandler() == handler'),'connection and stale state guards');
yes(session.includes('(!enabled && state.allowed())'),'closed sessions cannot re-enable');
yes(client.includes('registerFlightActivity')&&client.includes('registerMagicActivity'),'flight and horn visual registration');
yes(client.includes('flightOverride.close()')&&client.includes('magicOverride.close()'),'both registrations disposed');
yes(read('src/client/java/top/csituka/magicaland/gameplay/client/RemoteToolClient.java').includes('UnicornLevitationClient.init();'),'initialized');
yes(read('src/client/java/top/csituka/magicaland/gameplay/client/race/RaceClient.java').includes('UnicornLevitationClient.clear();'),'race reset');
yes(client.includes('if (client.isPaused()) return;'),'integrated pause freezes lease clock');
yes(client.includes('client.currentScreen != null')&&client.includes('!client.isWindowFocused()'),'menus and focus only zero raw input');
yes(!client.includes('SESSION.begin(false)'),'no automatic unarmed sessions');
yes(playerInput.includes('canSprint()Z')&&playerInput.includes('blocksSprinting()'),'native sprint gate while controlled');
console.log(`LevitationClientStructureTest: ${checks} checks PASS`);
